### ISSUE TITLE
Nestjs Logger 기능 추가 및 logging 예시 추가

### ISSUE THREAD

**Issue by SH9480P** [skkuding/codedang#1121]
### Describe the problem and solution

#1031 에서 Nestjs의 빌트인 로거를 Pino로 변경한 바 있습니다.
본 issue로 Pino 및 Prisma logging 옵션을 추가하여 로그 기능을 추가하고 로그 가독성을 증가시킬 예정입니다.
또한, 예시를 들기 위해 User 모듈에 로깅을 시험적으로 적용할 예정입니다.

### TODOS

- [x] pino-pretty 사용 시 개행되어 나타나는 context를 한 줄로 만들기
- [x] prisma logging 적용하기
- [x] User 모듈에 Info 레벨, debug 레벨 로깅 적용하기

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue
